"""add organizations table and user role status

Revision ID: 07815c93a335
Revises: af6587e6e0cf
Create Date: 2026-03-15 21:06:22.051340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07815c93a335'
down_revision = 'af6587e6e0cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('close_org_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_close_org_id'), ['close_org_id'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=32), server_default='member', nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=32), server_default='active', nullable=False))
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_column('status')
        batch_op.drop_column('role')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_close_org_id'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
