"""make rotation_member_id nullable in assignment_logs

Revision ID: 1337bb89fe85
Revises: a1b2c3d4e5f6
Create Date: 2026-03-20 14:55:43.738957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1337bb89fe85'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_logs', schema=None) as batch_op:
        batch_op.alter_column('rotation_member_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('organizations_close_org_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_organizations_close_org_id'))
        batch_op.create_index(batch_op.f('ix_organizations_close_org_id'), ['close_org_id'], unique=True)

    with op.batch_alter_table('rotation_members', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_rotation_members_rotation_user'), type_='unique')
        batch_op.create_unique_constraint('uq_rotation_user', ['rotation_id', 'close_user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rotation_members', schema=None) as batch_op:
        batch_op.drop_constraint('uq_rotation_user', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_rotation_members_rotation_user'), ['rotation_id', 'close_user_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_close_org_id'))
        batch_op.create_index(batch_op.f('ix_organizations_close_org_id'), ['close_org_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('organizations_close_org_id_key'), ['close_org_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('assignment_logs', schema=None) as batch_op:
        batch_op.alter_column('rotation_member_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
