"""add conditions to rotations

Revision ID: 1d684a59074f
Revises: 5439aa827622
Create Date: 2026-03-13 23:28:21.308028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d684a59074f'
down_revision = '5439aa827622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filters_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('custom_field_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('custom_field_label', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('overwrite_existing', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rotations', schema=None) as batch_op:
        batch_op.drop_column('overwrite_existing')
        batch_op.drop_column('custom_field_label')
        batch_op.drop_column('custom_field_id')
        batch_op.drop_column('filters_json')

    # ### end Alembic commands ###
