"""add seeded_lead_ids to queues

Revision ID: 3d4a636f309f
Revises: 4a3b7be057c0
Create Date: 2026-03-19 14:36:58.563093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d4a636f309f'
down_revision = '4a3b7be057c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeded_lead_ids', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queues', schema=None) as batch_op:
        batch_op.drop_column('seeded_lead_ids')

    # ### end Alembic commands ###
