"""composite unique on close_user_id and close_org_id

Revision ID: 4a3b7be057c0
Revises: 07815c93a335
Create Date: 2026-03-18 21:28:16.919596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a3b7be057c0'
down_revision = '07815c93a335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_close_user_id'))
        batch_op.create_index(batch_op.f('ix_users_close_user_id'), ['close_user_id'], unique=False)
        batch_op.create_unique_constraint('uq_users_close_user_org', ['close_user_id', 'close_org_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_close_user_org', type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_close_user_id'))
        batch_op.create_index(batch_op.f('ix_users_close_user_id'), ['close_user_id'], unique=True)

    # ### end Alembic commands ###
