"""initial

Revision ID: 5439aa827622
Revises: 
Create Date: 2026-03-08 07:10:00.101821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5439aa827622'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('close_user_id', sa.String(length=64), nullable=False),
    sa.Column('close_org_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_close_org_id'), ['close_org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_close_user_id'), ['close_user_id'], unique=True)

    op.create_table('rotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('close_org_id', sa.String(length=64), nullable=False),
    sa.Column('current_index', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rotations_close_org_id'), ['close_org_id'], unique=False)

    op.create_table('rotation_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rotation_id', sa.Integer(), nullable=False),
    sa.Column('close_user_id', sa.String(length=64), nullable=False),
    sa.Column('close_user_email', sa.String(length=255), nullable=True),
    sa.Column('close_user_name', sa.String(length=255), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rotation_id'], ['rotations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rotation_id', 'close_user_id', name='uq_rotation_user')
    )
    with op.batch_alter_table('rotation_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rotation_members_rotation_id'), ['rotation_id'], unique=False)

    op.create_table('assignment_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rotation_id', sa.Integer(), nullable=False),
    sa.Column('rotation_member_id', sa.Integer(), nullable=False),
    sa.Column('close_lead_id', sa.String(length=64), nullable=False),
    sa.Column('close_lead_name', sa.String(length=255), nullable=True),
    sa.Column('close_user_id', sa.String(length=64), nullable=False),
    sa.Column('close_user_name', sa.String(length=255), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rotation_id'], ['rotations.id'], ),
    sa.ForeignKeyConstraint(['rotation_member_id'], ['rotation_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignment_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_logs_close_lead_id'), ['close_lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_logs_rotation_id'), ['rotation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_logs_rotation_member_id'), ['rotation_member_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_logs_rotation_member_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_logs_rotation_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_logs_close_lead_id'))

    op.drop_table('assignment_logs')
    with op.batch_alter_table('rotation_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rotation_members_rotation_id'))

    op.drop_table('rotation_members')
    with op.batch_alter_table('rotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rotations_close_org_id'))

    op.drop_table('rotations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_close_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_close_org_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
