"""add distributions table and refactor assignment logs

Revision ID: cae22ca131e3
Revises: 1d684a59074f
Create Date: 2026-03-15 16:15:36.794830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cae22ca131e3'
down_revision = '1d684a59074f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rotation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('distribution_type', sa.String(length=32), nullable=False),
    sa.Column('filters_json', sa.JSON(), nullable=True),
    sa.Column('custom_field_id', sa.String(length=64), nullable=True),
    sa.Column('custom_field_label', sa.String(length=255), nullable=True),
    sa.Column('overwrite_existing', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rotation_id'], ['rotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('distributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distributions_rotation_id'), ['rotation_id'], unique=False)

    with op.batch_alter_table('assignment_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distribution_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_assignment_logs_rotation_id'))
        batch_op.create_index(batch_op.f('ix_assignment_logs_distribution_id'), ['distribution_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('assignment_logs_rotation_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'distributions', ['distribution_id'], ['id'])
        batch_op.drop_column('rotation_id')

    with op.batch_alter_table('rotations', schema=None) as batch_op:
        batch_op.drop_column('custom_field_id')
        batch_op.drop_column('overwrite_existing')
        batch_op.drop_column('filters_json')
        batch_op.drop_column('is_active')
        batch_op.drop_column('custom_field_label')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_field_label', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('filters_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('overwrite_existing', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('custom_field_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))

    with op.batch_alter_table('assignment_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotation_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('assignment_logs_rotation_id_fkey'), 'rotations', ['rotation_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_assignment_logs_distribution_id'))
        batch_op.create_index(batch_op.f('ix_assignment_logs_rotation_id'), ['rotation_id'], unique=False)
        batch_op.drop_column('distribution_id')

    with op.batch_alter_table('distributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distributions_rotation_id'))

    op.drop_table('distributions')
    # ### end Alembic commands ###
